- name: Copy redis yum repo
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Install redis
  ansible.builtin.yum:
    name: redis
    state: installed

- name: update listen address
  replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Satrt redis
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes