- name: copy mongodb repo file
  copy:
    src: /home/centos/Ansible/roles/mongodb/files/mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: install mongodb
  yum:
    name: mongodb-org
    state: installed

- name: update listen address
  replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: restart mongodb
  service:
    name: mongod
    state: restarted
    enabled: yes

- name: Download and Extrat mongodb
  unarchive:
    src: https://github.com/roboshop-devops-project/mongodb/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: load  schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop:
    - catalogue
    - users
