- name: Sample play
  hosts: all
  tasks:
    - name: Hello world task
      debug:
        msg: Hello world
    - name: register a variable
      shell:
        uptime
      register: OUT
    - name: set_fact variable
      set_fact:
        - OUTPUT: "{{OUT.stdout}}"
    - name: output from set_fact
      debug:
        msg: "{{OUTPUT}}"