- name: install Nginx
  yum:
    name: nginx
    state: installed
- name: start nginx
  service:
    name: nginx
    state: started

- name: Download and Extrat frontend
  unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: cleanup old nginx content
  file:
    path: /usr/share/nginx/html
    state: absent

- name: copy the frontend content to nginx path
  copy:
    src: /tmp/frontend-main/
    dest: /usr/share/nginx/html
    remote_src: yes