- name: install Nginx
  yum:
    name: nginx
    state: installed

- name: download and Extract {{COMPONENT}}
  include_role:
    name: common
    tasks_from: download # this line is required when tasks/download.yaml instead of main.yml

- name: cleanup old nginx content
  file:
    path: /usr/share/nginx/html
    state: absent

- name: copy the frontend content to nginx path
  copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html
    remote_src: yes

- name: copy roboshop configuration
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  notify: Restart Nginx

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes