- name: setup YUM repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: install MySQL
  ansible.builtin.yum:
    name:
      - mysql-community-server
      - MySQL-python
    state: installed

- name: satrt MySQL
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Fetch default root password
  ansible.builtin.shell:
    grep "temporary password" /var/log/mysqld.log | awk '{print $NF}'
  register: temp_password

- name: update mysql root password
  community.mysql.mysql_info:
    login_user: root
    login_password: RoboShop@1
  ignore_errors: yes
  register: mysql_stat

- name: Reset password block
  when: mysql_stat.failed
  block:
    - name: Grab root password
      ansible.builtin.shell: grep "temporary password" /var/log/mysqld.log | awk '{print $NF}'
      register: DEFAULT_ROOT_PASSWORD

    - name: copy sql password file
      ansible.builtin.copy:
        src: custompass.sql
        dest: /tmp/changedrootpass.sql

    - name: Reset MYSQL password
      ansible.builtin.shell: mysql --connect-expired-password -uroot -p"{{DEFAULT_ROOT_PASSWORD}}" </tmp/changedrootpass.sql







