- name: Configuring YUM repo
  ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -

- name: Install NodeJS
  ansible.builtin.yum:
    name:
    - nodejs
    - gcc-c++
    state: installed

- name: Add application user
  ansible.builtin.user:
    name: roboshop
    comment: Roboshop appilcation user

- name: download and Extract {{COMPONENT}}
  include_role:
    name: common
    tasks_from: download


