- name: Add application user
  ansible.builtin.user:
    name: roboshop
    comment: Roboshop appilcation user
  register: APP_USER_REGISTER


########## Download rom GitHub #################
#- name: Download and Extract {{COMMON_COMPONENT}}
#  unarchive:
#    src: https://github.com/roboshop-devops-project/{{COMMON_COMPONENT}}/archive/main.zip
#    dest: /tmp
#    remote_src: yes
#################################################

- name: Download and Extract from NEXUS repository {{COMMON_COMPONENT}}
  unarchive:
    src: http://44.195.41.117:8081/repository/cart/cart-1.0.2.zip
    dest: /tmp
    remote_src: yes

- name: Removing old content file
  ansible.builtin.file:
    path: /home/roboshop/{{COMMON_COMPONENT}}/
    state: absent

- name: Add app content
  ansible.builtin.copy:
    src: /tmp/{{COMMON_COMPONENT}}-main/
    dest: /home/roboshop/{{COMMON_COMPONENT}}/
    remote_src: yes
  become_user: roboshop



