- name: Add application user
  ansible.builtin.user:
    name: roboshop
    comment: Roboshop appilcation user
  register: APP_USER_REGISTER

- name: Removing old content file
  ansible.builtin.file:
    path: { { APP_LOCATION } }
    state: absent
########## Download rom GitHub #################
#- name: Download and Extract {{COMMON_COMPONENT}}
#  unarchive:
#    src: https://github.com/roboshop-devops-project/{{COMMON_COMPONENT}}/archive/main.zip
#    dest: /tmp
#    remote_src: yes
#################################################

- name: Download and Extract from NEXUS repository {{COMMON_COMPONENT}}
  unarchive:
    src: http://nexus.egaroboshop.online:8081/repository/{{COMMON_COMPONENT}}/{{COMMON_COMPONENT}}-1.0.0.zip
    dest: { { APP_LOCATION } }
    remote_src: yes
  become_user: roboshop
#
#- name: Add app content
#  ansible.builtin.copy:
#    src: /tmp/{{COMMON_COMPONENT}}-main/
#    dest: /home/roboshop/{{COMMON_COMPONENT}}/
#    remote_src: yes
#  become_user: roboshop



