- name: Configuring YUM repo
  ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -

- name: Install NodeJS
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: Setup App user, download and Extract {{COMMON_COMPONENT}}
  include_role:
    name: common
    tasks_from: download
  vars:
    - APP_LOCATION: "/home/roboshop/{{COMMON_COMPONENT}}"

- name: Install NodeJS dependecies based on package.json
  community.general.npm:
    path: /home/roboshop/{{COMMON_COMPONENT}}

- name: setup systemd
  include_role:
    name: common
    tasks_from: systemd




