- name: Install Python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Setup App user, download and Extract {{COMMON_COMPONENT}}
  include_role:
    name: common
    tasks_from: download

- name: Install specified python requirements
  pip:
    requirements: /home/roboshop/{{COMMON_COMPONENT}}/requirements.txt
    executable: pip3

- name: Update UserID in APP configuration
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{COMMON_COMPONENT}}/{{COMMON_COMPONENT}}.ini
    regexp: '^uid'
    line: uid = {{APP_USER_REGISTER.uid}}

- name: Update group in APP configuration
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{COMMON_COMPONENT}}/{{COMMON_COMPONENT}}.ini
    regexp: '^gid'
    line: gid = {{APP_USER_REGISTER.group}}

- name: setup systemd
  include_role:
    name: common
    tasks_from: systemd




